apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: application
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  LIBRENMS_MYSQL_DATABASE: "librenms"
  LIBRENMS_MEMORY_LIMIT: {{ .Values.Application.memoryLimit | quote }}
  LIBRENMS_BASE_URL: {{ coalesce .Values.Application.baseURL ( cat "http://" .Values.Application.ingressHost .Values.Application.ingressPath | nospace ) | quote }}
  {{- if .Values.snmpPing.enabled }}
  LIBRENMS_SNMP_PING: "true"
  LIBRENMS_SNMP_PING_RTT: {{ .Values.snmpPing.recordRTT | quote }}
  {{- else }}
  LIBRENMS_SNMP_PING: "false"
  LIBRENMS_SNMP_PING_RTT: "false"
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: dispatcher
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  LIBRENMS_DISPATCHER_POLLER_WORKERS: {{ .Values.Dispatcher.pollerWorkers | quote }}
  LIBRENMS_DISPATCHER_DISCOVERY_WORKERS: {{ .Values.Dispatcher.discoveryWorkers | quote }}
  LIBRENMS_DISPATCHER_SERVICES_WORKERS: {{ .Values.Dispatcher.serviceWorkers | quote }}
  LIBRENMS_DISPATCHER_LOG_LEVEL: {{ .Values.Dispatcher.logLevel | quote }}
