{{- range $name := tuple "nimbus" "supervisor" "ui" }}
{{- $fullname := include (print "storm." $name ".fullname") $ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
  labels:
    chart: {{ template "storm.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  storm.yaml: |-
    storm.zookeeper.servers:
{{ include "storm.zookeeper.serverlist.yaml" $ | indent 6 }}
    storm.zookeeper.port: {{ include "storm.zookeeper.port" $ }}
    nimbus.seeds:
      - {{ include "storm.nimbus.fullname" $ }}
    nimbus.thrift.port: {{ $.Values.nimbus.service.port }}
    storm.log4j2.conf.dir: /log4j2
    storm.local.hostname: {{ $fullname }}

---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "storm.logging.name" . }}
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $files := .Files }}
  {{- range tuple "cluster.xml" "worker.xml" }}
  {{ . }}: |-
{{ $files.Get . | indent 4 }}
  {{- end }}
