{{- range $name := tuple "nimbus" "supervisor" "ui" }}
{{- $fullname := include (print "storm." $name ".fullname") $ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
  labels:
    chart: {{ template "storm.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  storm.yaml: |-
    storm.zookeeper.servers:
{{ include "storm.zookeeper.serverlist.yaml" $ | indent 6 }}
    storm.zookeeper.port: {{ include "storm.zookeeper.port" $ }}
    nimbus.seeds:
    {{- range $i, $e := until (int $.Values.nimbus.replicaCount) }}
    - {{ template "storm.nimbus.fullname" $ }}-{{ $i }}.{{ template "storm.nimbus.fullname" $ }}
    {{- end }}
    nimbus.thrift.port: {{ $.Values.nimbus.service.port }}
    storm.log4j2.conf.dir: /log4j2
    storm.local.dir: /data
    storm.log.dir: /logs
    nimbus.childopts: {{ $.Values.nimbus.childopts }}
    supervisor.childopts: {{ $.Values.supervisor.childopts }}
    supervisor.worker.heap.memory.mb: {{ $.Values.supervisor.worker.heap_memory_mb }}
    ui.childopts: {{ $.Values.ui.childopts }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "storm.logging.name" . }}
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $files := .Files }}
  {{- range tuple "cluster.xml" "worker.xml" }}
  {{ . }}: |-
{{ $files.Get . | indent 4 }}
  {{- end }}
