apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: redis
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
  - name: redis
    port: {{ .Values.redis.servicePort }}
    targetPort: redis
---
{{- if eq .Values.redis.storage.type "dynamic" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.storage.class }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
---
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: redis
  labels:
    application: librenms
spec:
  serviceName: redis
  selector:
    matchLabels:
      component: redis
  replicas: 1
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      name: redis
      labels:
        application: librenms
        component: redis
    spec:
      {{- if and (eq .Values.redis.storage.type "dynamic") .Values.redis.storage.subpathRequired }}
      initContainers:
      - name: create-subpath
        image: {{ .Values.subpath.image.repository }}:{{ .Values.subpath.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: SUBPATHS
          value: "data"
        - name: OWNER
          value: "999"
        - name: GROUP
          value: "1000"
        volumeMounts:
        - name: redis-volume
          mountPath: /volume
      {{- end }}
      containers:
      - name: redis
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: redis
        env:
        - name: REDIS_REQUIRED_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application
              key: librenms_redis_password
        ports:
        - name: redis
          containerPort: {{ .Values.redis.providerPort }}
          protocol: TCP
        volumeMounts:
        - name: redis-volume
          subPath: data
          mountPath: /data
      volumes:
      - name: redis-volume
        {{- if eq .Values.redis.storage.type "temporary" }}
        emptyDir: {}
        {{- else if eq .Values.redis.storage.type "static" }}
        persistentVolumeClaim:
          claimName: {{ required "the name of the pre-configured Redis persistent volume claim must be provided (librenmsServices.redis.storage.claimName)" .Values.redis.storage.claimName }}
        {{- else }}
        persistentVolumeClaim:
          claimName: redis-volume-claim
        {{- end }}
