apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "siembol.alerting.deploy.rules.fullname" . }}
spec:
  template:
    spec:
      initContainers:
      {{/* Waiting for nimbus to be up, as it would mean that the zookeeper cluster is stable */}}
      - name: init-{{ include "storm.nimbus.fullname" . }}
        image: busybox
        command: ["sh", "-c", "until nc -w10 {{ include "storm.nimbus.fullname" . }} 6627 </dev/null; do echo waiting for {{ include "storm.nimbus.fullname" . }}; sleep 10; done"]
      containers:
      - name: {{ template "siembol.alerting.deploy.rules.name" . }}
        image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
        imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
        command:
          - /bin/bash
          - -o
          - pipefail
          - -euc
          - >
            server={{- include "siembol.zookeeper.server" . | quote -}};
            zkCli.sh -server ${server} get /siembol >/dev/null || zkCli.sh -server ${server} create /siembol >/dev/null;
            zkCli.sh -server ${server} get /siembol/alerting >/dev/null || zkCli.sh -server ${server} create /siembol/alerting >/dev/null;
            zkCli.sh -server ${server} set /siembol/alerting '{"rules_version":1,"tags":[{"tag_name":"detection_source","tag_value":"siembol_alerts"}],"rules":[{"rule_name":"test_rule","rule_version":1,"rule_author":"dummy","rule_protection":{"max_per_hour":100,"max_per_day":10000},"rule_description":"test rule - is_alert is equal to true","source_type":"secret","matchers":[{"matcher_type":"REGEX_MATCH","is_negated":false,"field":"is_alert","data":"(?i)true"}]}]}' >/dev/null;
            zkCli.sh -server ${server} get /siembol/synchronise >/dev/null || zkCli.sh -server ${server} create /siembol/synchronise >/dev/null;
            zkCli.sh -server ${server} set /siembol/synchronise '{}' >/dev/null;
            zkCli.sh -server ${server} get /siembol/cache >/dev/null || zkCli.sh -server ${server} create /siembol/cache >/dev/null;
            zkCli.sh -server ${server} set /siembol/cache '{}' >/dev/null;
      restartPolicy: Never
