apiVersion: v2
appVersion: 1.2.3
version: 1.0.9
description: Apache Storm is a free and open source distributed realtime computation
  system.
home: http://storm.apache.org/
icon: http://storm.apache.org/images/logo.png
keywords:
- storm
- zookeeper
maintainers:
- email: jorwalk@gmail.com
  name: jorwalk
- email: stackedsax@users.noreply.github.com
  name: stackedsax
name: storm
sources:
- https://github.com/G-Research/charts/src/storm
- https://github.com/G-Research/charts/storm
- https://github.com/apache/storm
dependencies:
- name: zookeeper
  version: ~6.5.2
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled