# Default values for storm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""
name: storm
enabled: true

nimbus:
  replicaCount: 2
  image:
    repository: storm
    tag: 1.2.3
    pullPolicy: IfNotPresent
  service:
    name: nimbus
    type: ClusterIP
    port: 6627
  childopts: "-Xmx1024m -ea"
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

supervisor:
  replicaCount: 3
  image:
    repository: storm
    tag: 1.2.3
    pullPolicy: IfNotPresent
  service:
    name: supervisor
    port: 6700
  childopts: "-Xmx256m -ea"
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  worker:
    heap_memory_mb: 768

ui:
  enabled: true
  replicaCount: 1
  image:
    repository: storm
    tag: 1.2.3
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    name: ui
    port: 8080
  childopts: "-Xmx768m -ea"
  resources: {}
  ingress:
    enabled: false
    annotations: {}
    tls: []

persistence:
  enabled: true
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  
  data:
    size: 1Gi
    annotations: {}
    # existingClaim:
  
  logs:
    size: 1Gi
    annotations: {}
    # existingClaim:

zookeeper:
  enabled: true
  replicaCount: 1
  # # if using an external zookeeper, you need to set the server names below
  # servers: 
  #  - "example.external.zookeeper1"
  #  - "example.external.zookeeper2"
  #  - "example.external.zookeeper3"
  # # external server port
  # port: 2181
