apiVersion: v1
kind: Service
metadata:
  name: {{ template "storm.nimbus.fullname" . }}
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ template "storm.namespace" . }}
spec:
  type: {{ .Values.nimbus.service.type }}
  ports:
  - port: {{ .Values.nimbus.service.port }}
    name: {{ .Values.nimbus.service.name }}
  selector:
    app: {{ template "storm.nimbus.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "storm.nimbus.fullname" . }}-headless
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ template "storm.namespace" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.nimbus.service.port }}
    name: {{ .Values.nimbus.service.name }}
  selector:
    app: {{ template "storm.nimbus.name" . }}
    release: {{ .Release.Name }}