apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "storm.supervisor.fullname" . }}
  labels:
    app: {{ template "storm.supervisor.name" . }}
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podManagementPolicy: "Parallel"
  serviceName: {{ template "storm.supervisor.fullname" . }}
  replicas: {{ .Values.supervisor.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "storm.supervisor.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "storm.supervisor.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-{{ template "storm.nimbus.fullname" . }}
        image: "{{ .Values.supervisor.image.repository }}:{{ .Values.supervisor.image.tag }}"
        imagePullPolicy: {{ .Values.supervisor.image.pullPolicy }}
        command: ["sh", "-c", "until storm list; do echo waiting for {{ template "storm.nimbus.fullname" . }}; sleep 10; done"]
        volumeMounts:
          - mountPath: "/conf"
            name: storm-configmap
      containers:
      - name: {{ .Values.supervisor.service.name }}
        image: "{{ .Values.supervisor.image.repository }}:{{ .Values.supervisor.image.tag }}"
        imagePullPolicy: {{ .Values.supervisor.image.pullPolicy }}
        command: ["storm", "supervisor", "-c", "storm.local.hostname=$(STORM_LOCAL_HOSTNAME).{{ template "storm.supervisor.fullname" . }}"]
        ports:
        - containerPort: {{ .Values.supervisor.service.port }}
        resources:
{{ toYaml .Values.supervisor.resources | indent 10 }}
        env:
        - name: STORM_DATA_DIR
          value: /data
        - name: STORM_LOG_DIR
          value: /logs
        - name: STORM_LOCAL_HOSTNAME
          valueFrom:
            fieldRef: {fieldPath: metadata.name}
        volumeMounts:
          - mountPath: "/conf"
            name: storm-configmap
          - mountPath: "/log4j2"
            name: storm-logging-config
          - name: data
            mountPath: /data
          - name: data-log
            mountPath: /logs
      volumes:
        - name: storm-configmap
          configMap:
            name: {{ template "storm.supervisor.fullname" . }}
        - name: storm-logging-config
          configMap:
            name: {{ template "storm.logging.name" . }}
        {{- if and .Values.persistence.enabled .Values.persistence.data.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl .Values.persistence.data.existingClaim .) }}
        {{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if and .Values.persistence.enabled .Values.persistence.logs.existingClaim }}
        - name: data-log
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl .Values.persistence.logs.existingClaim .) }}
        {{- else if and ( not .Values.persistence.enabled ) .Values.logs }}
        - name: data-log
          emptyDir: {}
        {{- end }}
  {{- if and .Values.persistence.enabled (not (and .Values.persistence.data.existingClaim .Values.persistence.logs.existingClaim) )}}
  volumeClaimTemplates:
    {{- if not .Values.persistence.data.existingClaim }}
    - metadata:
        name: data
        annotations:
        {{- range $key, $value := .Values.persistence.data.annotations }}
          {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size | quote }}
        {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 8 }}
    {{- end }}
    {{- if and (not .Values.persistence.logs.existingClaim) }}
    - metadata:
        name: data-log
        annotations:
        {{- range $key, $value := .Values.persistence.logs.annotations }}
          {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.logs.size | quote }}
        {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 8 }}
    {{- end }}
  {{- end }}