apiVersion: v1
kind: Service
metadata:
  name: {{ template "storm.supervisor.fullname" . }}
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ template "storm.namespace" . }}
spec:
  type:  {{ .Values.supervisor.service.type }}
  ports:
  {{- range $i, $e := until (int $.Values.supervisor.slots) }}
  - port: {{add $i 6700}}
    name: slot-{{ $i }}
  {{- end }}
  selector:
    app: {{ template "storm.supervisor.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "storm.supervisor.fullname" . }}-headless
  labels:
    chart: {{ template "storm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ template "storm.namespace" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  {{- range $i, $e := until (int $.Values.supervisor.slots) }}
  - port: {{add $i 6700}}
    name: slot-{{ $i }}
  {{- end }}
  selector:
    app: {{ template "storm.supervisor.name" . }}
    release: {{ .Release.Name }}
