{{- if .Values.ui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "siembol.ui.fullname" $ }}
  annotations:
    cert-manager.io/issuer: ca-issuer
spec:
  {{ if .Values.tls.enabled -}}
  tls:
  - hosts: 
    - {{ .Values.ui.ingress.hostname }}
    - {{ .Values.rest.ingress.hostname }}
    - {{ .Values.manager.ingress.hostname }}
    - {{ .Values.storm.ingress.hostname }}
    secretName: {{ include "siembol.ui.fullname" $ }}-tls
  {{ end }}
  rules:
  - host: {{ .Values.ui.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "siembol.ui.fullname" $ }}
            port: 
              number: 8080
  - host: {{ .Values.rest.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "siembol.rest.fullname" $ }}
            port: 
              number: 8081
  - host: {{ .Values.manager.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "siembol.manager.appname.fullname" $ }}
            port: 
              number: 8082
  - host: {{ .Values.storm.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: siembol-storm-ui
            port: 
              number: 8080
{{- end -}}