kind: Service
apiVersion: v1
metadata:
  name: {{ include "siembol.rest.fullname" $ }}
  labels:
    metrics: "true"
spec:
  selector:
    app: {{ include "siembol.rest.fullname" $ }}
  ports:
  - protocol: TCP
    port: 8081
    name: web
  