memcached:
  connectionRequests: 10
  image:
    repository: docker.io/tpboudreau/librenms-memcached
    tag: 0.1.1
  logLevel: ""
  providerPort: 11211
  servicePort: 11211
  threadCount: 2
mysql:
  external:
    address: null
    enabled: false
    port: 3306
  image:
    repository: docker.io/tpboudreau/librenms-mysql
    tag: 0.1.1
  prepareDatabaseImage:
    repository: docker.io/tpboudreau/librenms-prepare-mysql
    tag: 0.1.1
  prepareVolumeImage:
    repository: docker.io/tpboudreau/librenms-mysql-prepare-volume
    tag: 0.1.1
  providerPort: 33306
  readinessDelay: 15
  servicePort: 3306
  storage:
    claimName: null
    class: ssd
    size: 100Gi
    subpathRequired: true
    type: dynamic
redis:
  image:
    repository: docker.io/tpboudreau/librenms-redis
    tag: 0.1.1
  logLevel: notice
  providerPort: 36379
  servicePort: 6379
  storage:
    claimName: null
    class: ssd
    size: 100Gi
    subpathRequired: true
    type: dynamic
rrdcached:
  chunkSize: 2
  external:
    address: null
    enabled: false
    port: 42217
  flushInterval: 600
  image:
    repository: docker.io/tpboudreau/librenms-rrdcached
    tag: 0.1.1
  logLevel: LOG_NOTICE
  providerPort: 42217
  servicePort: 42217
  storage:
    claimName: null
    class: standard
    size: 100Gi
    subpathRequired: true
    type: dynamic
  threadCount: 2
  writeDelay: 5
  writeInterval: 300
subpath:
  image:
    repository: docker.io/tpboudreau/librenms-subpath
    tag: 0.1.1
